-- WAQTF ANY 4 IMPORTANT COLUMNS FROM CORPORATES TABLE UNDER SQL_INVENTORY DATABASE
USE SQL_INVENTORY;
SELECT 
	COLLEAGUE_ID,
    POSITION,
    REPORTING_ID,
    SALARY
FROM CORPORATES;


-- WAQTF CUSTOMERS HAVING POINTS GREATER THAN 2000 IN CUSTOMERS TB UNDER SQL_STORE DB
USE SQL_STORE;
SELECT * 
FROM CUSTOMERS
WHERE POINTS > 2000;


-- WAQTF EMPLOYEES TABLE FROM HR DB AND GIVE AN INCREMENT OF 5K TO EVERYBODY AND CALL IT DIWALI_BONUS
USE SQL_HR;
SELECT * ,
	   SALARY + 5000 AS "DIWALI BONUS"
FROM EMPLOYEES;

-- WAQTF INVOICE_TOTAL GREATER THAN 150 AND CLIENT_ID > 2 IN INVOICES TB UNDER INVOICING DB
USE SQL_INVOICING;
SELECT * 
FROM INVOICES 
WHERE (INVOICE_TOTAL > 150 ) AND (CLIENT_ID > 2);

-- WAQTF ONLY THOSE OFFICE_ID WHICH BELONG TO MAHARASHTRA AND GUJARAT STATES IN OFFICES TB UNDER HR DB
USE SQL_HR;
SELECT OFFICE_ID
FROM OFFICES
WHERE STATE IN ("MH","GH");

-- FETCH ONLY 1,2,3,4,6,7,8,9,11,12 ID's FROM OFFICES TB UNDER HR DB
USE SQL_HR;
SELECT * 
FROM OFFICES
WHERE NOT OFFICE_ID IN (5,10);

-- WAQTF NULL ENTRIES IN REPORTS_TO COLUMN OF EMP TB UNDER HR DB
USE SQL_HR;
SELECT * 
FROM EMPLOYEES
WHERE REPORTS_TO IS NULL;


-- WAQTF ALL OFFICE_ID EXCEPT 2 IN EMP TB UNDER HR DB (USE COMP OPERATOR)
USE SQL_HR;
SELECT * 
FROM EMPLOYEES
WHERE OFFICE_ID != 2;

-- WAQTF ONLY THOSE EMPLOYEES EARNING SALARY ABOVE 1L BUT YOU HAVE TO COMPULSORILY USE 'NOT' ALSO IN EMP TB UNDER HR DB
USE SQL_HR;
SELECT * 
FROM EMPLOYEES
WHERE NOT (SALARY < 100000);

-- WAQT GIVE AN INCREMENT OF 25% TO ONLY THOSE EMPLOYEES REPORTING TO OFFICE_ID 1, 2 IN EMP_NEW TB UNDER HR DB
USE SQL_HR;
SELECT * ,
		SALARY * 1.25 AS "INCREMENT SALARY"
FROM EMPLOYEES
WHERE OFFICE_ID IN (1,2);


-- WAQTF DISTINCT CLIENT_ID's FROM INVOICES TB UNDER INV DB
USE SQL_INVOICING;
SELECT DISTINCT CLIENT_ID
FROM CLIENTS;

-- WAQTF CUST EARNING POINTS BETW 500 AND 1500 IN CUST TB UNDER STORE DB
USE SQL_STORE;
SELECT * 
FROM CUSTOMERS
WHERE POINTS BETWEEN 500 AND 1500;

-- WAQTF CUST HAVING 0 AT ANY POSITION EXCEPT FIRST IN PHONE NUMBER FIELD IN CUST TB UNDER STORE DB
-- USE SQL_STORE;
-- SELECT * 
-- FROM CUSTOMERS 
-- WHERE PHONE REGEXP "^[1-9][0-9]*0[0-9]*$"; 
-- FOR EXAMPLE: 12304545,1003440,

-- ANS (TYP1)
SELECT *
FROM CUSTOMERS
WHERE PHONE REGEXP '^[1-9]' AND PHONE REGEXP 0;

-- ANS (TYP2)
SELECT * 
FROM CUSTOMERS 
WHERE PHONE NOT LIKE "0%" AND PHONE LIKE "%0%";


-- WAQTF CUST HAVING 'M' ANYWHERE IN FIRST_NAME FIELD IN CUST TB UNDER STORE DB
-- ANS (TYP-1)
USE SQL_STORE;
SELECT * 
FROM CUSTOMERS
WHERE FIRST_NAME LIKE "%M%";

-- ANS (TYP-2)
USE SQL_STORE;
SELECT * 
FROM CUSTOMERS
WHERE FIRST_NAME REGEXP "M";



-- WAQTF EMPLOYEES HAVING EITHER 'BH' AS THE STARTING TWO LETTERS OR 'GH' AS THE END TWO LETTERS IN LAST NAME COLUMN OF EMP TB UNDER HR DB (USE REGEXP)
USE SQL_HR;
SELECT * 
FROM EMPLOYEES
WHERE LAST_NAME REGEXP "^BH|GH$";


-- WAQT FETCH CUSTOMERS (STORE DB)EARNING POINTS UNDER 2K AND REARRANGE THE OUTPUT IN DESC ORDER
USE SQL_STORE;
SELECT * 
FROM CUSTOMERS
WHERE POINTS > 2000 
ORDER BY POINTS DESC;




-- WAQTF COSTLIEST 3 INVOICE TOTAL IN INV TB UNDER INVOICING DB
USE SQL_INVOICING;
SELECT INVOICE_TOTAL
FROM INVOICES
ORDER BY INVOICE_TOTAL DESC
LIMIT 3;