-- 1. INNER JOINS --
-- EXERCISE 1: USE SQL_HR DATABASE AND WAQ TO JOIN EMPLOYEES TABLE WITH OFFICES TABLE ON OFFICE_ID COLUMN.
USE SQL_HR;
SELECT * 
FROM EMPLOYEES EMP 
JOIN OFFICES OFFI 
ON EMP.OFFICE_ID = OFFI.OFFICE_ID;

-- Exercise 1.1: Use sql_store database and JOIN customers table with Orders table using customer_id column and select following columns. customer_id, first_name, phone, points, order_id, order_date, shipped_date, shipper_id.
USE SQL_STORE;
SELECT 
	CUS.CUSTOMER_ID,
    CUS.FIRST_NAME,
    CUS.PHONE,
    CUS.POINTS,
    ORD.ORDER_ID,
    ORD.ORDER_DATE,
    ORD.SHIPPED_DATE,
    ORD.SHIPPER_ID
FROM CUSTOMERS CUS 
JOIN ORDERS ORD 
ON CUS.CUSTOMER_ID = ORD.CUSTOMER_ID;


-- EXERCISE 1.2: USE SQL_STORE DATABASE & JOIN THE ORDER_ITEMS TABLE WITH THE PRODUCTS TABLE ON THE PRODUCT_ID COLUMN AND SELECT THE SPECIFIC COLUMNS OF YOUR CHOICE.
USE SQL_STORE;
SELECT 
	OI.ORDER_ID,
    OI.QUANTITY,
    OI.UNIT_PRICE,
    PO.NAME,
    PO.QUANTITY_IN_STOCK,
    PO.UNIT_PRICE
FROM ORDER_ITEMS OI
JOIN PRODUCTS PO 
ON OI.PRODUCT_ID = PO.PRODUCT_ID;


-- 2. JOINING ACROSS DATABASES
-- EXERCISE 03: JOIN PRODUCTS TABLE OF SQL_INVENTORY WITH ORDER_ITEM_NOTES TABLE OF SQL_STORE ON PRODUCT_ID AND SELECT SPECIFIC COLUMNS.
SELECT 
	PRO.PRODUCT_ID,
	PRO.NAME,
	PRO.QUANTITY_IN_STOCK,
	OIN.ORDER_ID,
	OIN.PRODUCT_ID,
	OIN.NOTE
FROM SQL_INVENTORY.PRODUCTS PRO
JOIN SQL_STORE.ORDER_ITEM_NOTES OIN 
ON PRO.PRODUCT_ID = OIN.PRODUCT_ID;

-- 3. SELF JOINS
-- EXERCISE 04: SELF JOIN EMPLOYEES TABLE OF SQL_HR AND GET THE EMPLOYEE_ID, FIRST_NAME, JOB_TITTLE AND FIRST_NAME OF THIER REPORTING MANAGER.
USE SQL_HR;
SELECT 
	E1.EMPLOYEE_ID,
    E1.FIRST_NAME,
    E1.JOB_TITLE,
    E2.FIRST_NAME
FROM EMPLOYEES E1 
JOIN EMPLOYEES E2 
ON E1.REPORTS_TO = E2.EMPLOYEE_ID;

-- 4.	JOINING MULTIPLE TABLES
-- EXERCISE 05: USE SQL_STORE DATABASE AND JOIN ORDERS TABLE, CUSTOMERS TABLE AND ORDER_STATUSES TABLE USING APPROPRIATE COLUMN AND GET THE DETAILS OF ORDER_ID, ORDER_DATE, CUSTOMER_ID, FIRST_NAME & ORDER STATUS.
USE SQL_STORE;
SELECT 
	ORD.ORDER_ID,
    ORD.ORDER_DATE,
    CUS.CUSTOMER_ID,
    CUS.FIRST_NAME,
    OS.ORDER_STATUS_ID AS ORDER_STATUS
FROM ORDERS ORD 
JOIN CUSTOMERS CUS 
ON ORD.CUSTOMER_ID = CUS.CUSTOMER_ID 
JOIN ORDER_STATUSES OS 
ON ORD.STATUS = OS.ORDER_STATUS_ID;

-- EXERCISE 06: USE THE ‘SQL_INVOICING’ DATABASE. JOIN THE ‘PAYMENTS’ TABLE WITH THE ‘CLIENTS’ TABLE 
-- USING THE ‘CLINETS_ID’ COLUMN AND THEN JOIN THE ‘PAYMENTS’ TABLE WITH THE ‘PAYMENT_METHODS’ TABLE 
-- USING THE ‘PAYMENT_METHOD’ COLUMN.

USE SQL_INVOICING;
SELECT 
	PAY.PAYMENT_ID,
    PAY.CLIENT_ID,
    PAY.INVOICE_ID,
    CLI.NAME,
    CLI.CITY,
    CLI.PHONE,
    PYM.NAME
FROM PAYMENTS PAY 
JOIN CLIENTS CLI 
ON PAY.CLIENT_ID = CLI.CLIENT_ID
JOIN PAYMENT_METHODS PYM 
ON PAY.PAYMENT_METHOD = PYM.PAYMENT_METHOD_ID;


-- 5.	COMPOUND JOIN CONDITIONS
-- EXERCISE 07: USE SQL_STORE DATABASE AND JOIN ORDER_ITEMS TABLE WITH ORDER_ITEM_NOTES TABLE ON ORDER_ID & PRODUCT_ID COLOUMN.

USE SQL_STORE;
SELECT * 
FROM ORDER_ITEMS OI
JOIN ORDER_ITEM_NOTES OIN
ON OI.ORDER_ID = OIN.ORDER_ID AND OI.PRODUCT_ID = OIN.PRODUCT_ID;



-- 6.	IMPLICIT JOIN SYNTAX
-- EXERCISE 08: WRITE IMPLICIT QUERY TO JOIN ORDERS TABLE AND ORDER_ITEMS TABLE OF SQL_STORE ON ORDER_ID COLUMN.
USE SQL_STORE;
SELECT * 
FROM ORDERS O,ORDER_ITEMS OI
WHERE O.ORDER_ID = OI.ORDER_ID;


-- 7.	CROSS JOINS
-- EXERCISE 09: WAQ TO PERFORM CROSS JOIN ON PRODUCTS TABLE AND ORDER_ITEMS TABLE OF SQL_STORE.
-- WRITE A QUERY IN BOTH WAYS. I.E. EXPLICIT & IMPLICIT QUERY.
-- EXPLICT
USE SQL_STORE;
SELECT * 
FROM PRODUCTS PRO 
CROSS JOIN ORDER_ITEMS OI;

-- IMPLICT 
USE SQL_STORE;
SELECT * 
FROM PRODUCTS PRO , ORDER_ITEMS OI;


-- 08.	NATURAL JOINS
-- EXERCISE 10: WAQ TO PERFORM NATURAL JOIN ON ORDERS TABLE AND CUSTOMERS TABLE OF SQL_STORE.

USE SQL_STORE;
SELECT * 
FROM ORDERS ORD 
NATURAL JOIN CUSTOMERS CUS;

-- ----------------------------------------------------------------------------------------------------
-- 09.	OUTER JOINS
-- IN OUTER JOINS WE HAVE 2 TYPES
-- 1.	LEFT JOIN
-- 2.	RIGHT JOIN

-- 1.	LEFT JOIN
-- EXERCISE 11: WAQ TO PERFORM LEFT JOIN ON ORDERS TABLE AND SHIPPERS TABLE OF SQL_STORE ON SHIPPER_ID AND GET THE DETAILS OF ORDER_ID, CUSTOMER_ID, ORDER_DATE, SHIPPED_DATE & SHIPPERS_NAME.

USE SQL_STORE;
SELECT 
	ORD.ORDER_ID,
    ORD.CUSTOMER_ID,
    ORD.ORDER_DATE,
    ORD.SHIPPED_DATE,
    SHP.NAME AS SHIPPERS_NAME
FROM ORDERS ORD 
LEFT JOIN SHIPPERS SHP 
ON ORD.SHIPPER_ID = SHP.SHIPPER_ID;

-- 2.	RIGHT JOIN -- 
-- EXERCISE 12: WAQ TO PERFORM RIGHT JOIN ON ORDERS TABLE AND CUSTOMERS TABLE OF SQL_STORE. AND COMPARE IT WITH LEFT JOIN RESULT.

USE SQL_STORE;
SELECT 
    ORD.CUSTOMER_ID,
    ORD.STATUS,
    ORD.SHIPPED_DATE,
    ORD.SHIPPER_ID,
	CUS.CUSTOMER_ID,
    CUS.FIRST_NAME,
    CUS.PHONE
FROM CUSTOMERS CUS
RIGHT JOIN ORDERS ORD
ON CUS.CUSTOMER_ID = ORD.CUSTOMER_ID;


-- 10.	OUTER JOIN ON MULTIPLE TABLES 
-- EXERCISE 13: WAQ TO PERFORM LEFT JOIN ON CUSTOMERS TABLE WITH ORDERS TABLE ON CUSTOMER_ID COLUMN, AND AGAIN PERFORM LEFT JOIN ON ORDERS TABLE WITH SHIPPERS TABLE WITH SHIPPER_ID COLUMN.

USE SQL_STORE;
SELECT * 
FROM CUSTOMERS CUS 
LEFT JOIN ORDERS ORD
ON CUS.CUSTOMER_ID = ORD.CUSTOMER_ID
LEFT JOIN SHIPPERS SH 
ON ORD.SHIPPER_ID = SH.SHIPPER_ID;

-- 11.	SELF-OUTER JOINS
-- EXERCISE 13: WAQ TO PERFORM SELF OUTER JOIN ON EMPLOYEES TABLE OF SQL_HR. AND COMPARE THE RESULT WITH NORMAL JOIN.

USE SQL_HR;
SELECT * 
FROM EMPLOYEES E1
LEFT JOIN EMPLOYEES E2 
ON E1.REPORTS_TO = E2.EMPLOYEE_ID;


-- 12.	THE USING CLAUSE
-- EXERCISE 14: USE SQL_STORE DATABASE AND JOIN CUSTOMERS TABLE WITH ORDERS TABLE USING CUSTOMER_ID COLUMN, AND ALSO JOIN ORDERS TABLE WITH SHIPPERS TABLE USING SHIPPER_ID COLUMN.

USE SQL_STORE;
SELECT * 
FROM CUSTOMERS CUS 
JOIN ORDERS ORD 
USING (CUSTOMER_ID) 
JOIN SHIPPERS
USING (SHIPPER_ID);

-- 13.	UNIONS
-- EXERCISE 15: USE SQL_STORE DATABASE & CUSTOMERS TABLE. WQD A TABLE HAVING CUSTOMERS LABELLED AS BRONZE, SILVER & GOLD BASED ON THEIR POINTS. BRONZE IF POINTS ARE LESS THAN 2000 & SILVER IF POINTS ARE BETWEEN 2000 TO 3000 AND GOLD IF POINTS ARE MORE THAN 3000.

USE SQL_STORE;
SELECT *,
"BRONZE" AS CATEGORY
FROM CUSTOMERS 
WHERE POINTS < 2000
UNION
SELECT *,
"SILVER" AS CATEGORY
FROM CUSTOMERS 
WHERE POINTS BETWEEN 2000 AND 3000
UNION 
SELECT *,
"GOLD" AS CATEGORY
FROM CUSTOMERS 
WHERE POINTS > 3000;

-- EXERCISE 16: USE SQL_HR DATABASE & EMPLOYEES TABLE. WRITE A QUERY TO DISPLAY EMPLOYEES RECORDS WITH RESPECTIVE THE OFFICE_ID THEY REPORT TO. MAKE A NEW COLUMN AND LABELLE IT AS DESIGNATION. GIVE DESIGNATION AS MANAGER TO EMPLOYEES WHO REPORTS TO OFFICE ID 1 AND ASSISTANT MANAGER TO THE EMPLOYEES WHO REPORTS TO OFFICE ID 2.

USE SQL_HR;
SELECT *,
"MANAGER TO EMPLOYEES" AS DESIGNATION
FROM EMPLOYEES
WHERE OFFICE_ID = 1
UNION 
SELECT *,
"ASSISTANT MANAGER TO EMPLOYEES" AS DESIGNATION
FROM EMPLOYEES
WHERE OFFICE_ID = 2;
