-- 1. INNER JOINS --
-- EXERCISE 1: USE SQL_HR DATABASE AND WAQ TO JOIN EMPLOYEES TABLE WITH OFFICES TABLE ON OFFICE_ID COLUMN.
USE SQL_HR;
SELECT * 
FROM EMPLOYEES
JOIN OFFICES 
USING (OFFICE_ID);

-- Exercise 1.1: Use sql_store database and JOIN customers table with Orders table using customer_id column and select following columns. customer_id, first_name, phone, points, order_id, order_date, shipped_date, shipper_id.
USE SQL_STORE;
SELECT 
	CUSTOMER_ID,
    FIRST_NAME,
    PHONE,
    POINTS,
    ORDER_ID,
    ORDER_DATE,
    SHIPPED_DATE,
    SHIPPER_ID
FROM CUSTOMERS 
JOIN ORDERS 
USING (CUSTOMER_ID);

-- EXERCISE 1.2: USE SQL_STORE DATABASE & JOIN THE ORDER_ITEMS TABLE WITH THE PRODUCTS TABLE ON THE PRODUCT_ID COLUMN AND SELECT THE SPECIFIC COLUMNS OF YOUR CHOICE.

USE SQL_STORE;
SELECT 
	*
FROM ORDER_ITEMS 
JOIN PRODUCTS 
USING (PRODUCT_ID);

-- 2. JOINING ACROSS DATABASES
-- EXERCISE 03: JOIN PRODUCTS TABLE OF SQL_INVENTORY WITH ORDER_ITEM_NOTES TABLE OF SQL_STORE ON PRODUCT_ID AND SELECT SPECIFIC COLUMNS.

SELECT 
    NAME,
    QUANTITY_IN_STOCK,
    UNIT_PRICE,
    NOTE
FROM SQL_INVENTORY.PRODUCTS SIP
JOIN 
SQL_STORE.ORDER_ITEM_NOTES  OI
ON SIP.PRODUCT_ID = OI.PRODUCT_ID;

-- 3. SELF JOINS
-- EXERCISE 04: SELF JOIN EMPLOYEES TABLE OF SQL_HR AND GET THE EMPLOYEE_ID, FIRST_NAME, JOB_TITTLE AND FIRST_NAME OF THIER REPORTING MANAGER.
SELECT * FROM sql_hr.employees;
USE SQL_HR;
SELECT 
      E1.EMPLOYEE_ID,
      E1.FIRST_NAME,
      E1.JOB_TITLE,
      E2.FIRST_NAME
FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON E1.REPORTS_TO = E2.EMPLOYEE_ID;

-- 4.	JOINING MULTIPLE TABLES
-- EXERCISE 05: USE SQL_STORE DATABASE AND JOIN ORDERS TABLE, CUSTOMERS TABLE AND ORDER_STATUSES TABLE USING APPROPRIATE COLUMN AND GET THE DETAILS OF ORDER_ID, ORDER_DATE, CUSTOMER_ID, FIRST_NAME & ORDER STATUS.

USE SQL_STORE;
SELECT * 
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID 
JOIN SHIPPERS SH 
ON O.SHIPPER_ID = SH.SHIPPER_ID 
JOIN ORDER_STATUSES OS 
ON SH.NAME = OS.NAME;

-- EXERCISE 06: USE THE ‘SQL_INVOICING’ DATABASE. JOIN THE ‘PAYMENTS’ TABLE WITH THE ‘CLIENTS’ TABLE 
-- USING THE ‘CLINETS_ID’ COLUMN AND THEN JOIN THE ‘PAYMENTS’ TABLE WITH THE ‘PAYMENT_METHODS’ TABLE 
-- USING THE ‘PAYMENT_METHOD’ COLUMN.

-- 5.	COMPOUND JOIN CONDITIONS
-- EXERCISE 07: USE SQL_STORE DATABASE AND JOIN ORDER_ITEMS TABLE WITH ORDER_ITEM_NOTES TABLE ON ORDER_ID & PRODUCT_ID COLOUMN.

-- 6.	IMPLICIT JOIN SYNTAX
-- EXERCISE 08: WRITE IMPLICIT QUERY TO JOIN ORDERS TABLE AND ORDER_ITEMS TABLE OF SQL_STORE ON ORDER_ID COLUMN.

-- 7.	CROSS JOINS
-- EXERCISE 09: WAQ TO PERFORM CROSS JOIN ON PRODUCTS TABLE AND ORDER_ITEMS TABLE OF SQL_STORE.
-- WRITE A QUERY IN BOTH WAYS. I.E. EXPLICIT & IMPLICIT QUERY.

-- 08.	NATURAL JOINS
-- EXERCISE 10: WAQ TO PERFORM NATURAL JOIN ON ORDERS TABLE AND CUSTOMERS TABLE OF SQL_STORE.

-- ----------------------------------------------------------------------------------------------------
-- 09.	OUTER JOINS
-- IN OUTER JOINS WE HAVE 2 TYPES
-- 1.	LEFT JOIN
-- 2.	RIGHT JOIN

-- 1.	LEFT JOIN
-- EXERCISE 11: WAQ TO PERFORM LEFT JOIN ON ORDERS TABLE AND SHIPPERS TABLE OF SQL_STORE ON SHIPPER_ID AND GET THE DETAILS OF ORDER_ID, CUSTOMER_ID, ORDER_DATE, SHIPPED_DATE & SHIPPERS_NAME.

-- 2.	RIGHT JOIN -- 
-- EXERCISE 12: WAQ TO PERFORM RIGHT JOIN ON ORDERS TABLE AND CUSTOMERS TABLE OF SQL_STORE. AND COMPARE IT WITH LEFT JOIN RESULT.

-- 10.	OUTER JOIN ON MULTIPLE TABLES 
-- EXERCISE 13: WAQ TO PERFORM LEFT JOIN ON CUSTOMERS TABLE WITH ORDERS TABLE ON CUSTOMER_ID COLUMN, AND AGAIN PERFORM LEFT JOIN ON ORDERS TABLE WITH SHIPPERS TABLE WITH SHIPPER_ID COLUMN.

-- 11.	SELF-OUTER JOINS
-- EXERCISE 13: WAQ TO PERFORM SELF OUTER JOIN ON EMPLOYEES TABLE OF SQL_HR. AND COMPARE THE RESULT WITH NORMAL JOIN.

-- 12.	THE USING CLAUSE
-- EXERCISE 14: USE SQL_STORE DATABASE AND JOIN CUSTOMERS TABLE WITH ORDERS TABLE USING CUSTOMER_ID COLUMN, AND ALSO JOIN ORDERS TABLE WITH SHIPPERS TABLE USING SHIPPER_ID COLUMN.

-- 13.	UNIONS
-- EXERCISE 15: USE SQL_STORE DATABASE & CUSTOMERS TABLE. WQD A TABLE HAVING CUSTOMERS LABELLED AS BRONZE, SILVER & GOLD BASED ON THEIR POINTS. BRONZE IF POINTS ARE LESS THAN 2000 & SILVER IF POINTS ARE BETWEEN 2000 TO 3000 AND GOLD IF POINTS ARE MORE THAN 3000.

-- EXERCISE 16: USE SQL_HR DATABASE & EMPLOYEES TABLE. WRITE A QUERY TO DISPLAY EMPLOYEES RECORDS WITH RESPECTIVE THE OFFICE_ID THEY REPORT TO. MAKE A NEW COLUMN AND LABELLE IT AS DESIGNATION. GIVE DESIGNATION AS MANAGER TO EMPLOYEES WHO REPORTS TO OFFICE ID 1 AND ASSISTANT MANAGER TO THE EMPLOYEES WHO REPORTS TO OFFICE ID 2.
