-- HOW TO OPEN A TABLE 
USE SQL_STORE;
SELECT * 
FROM CUSTOMERS; 

-- HOW TO WRITE A SPECIFIC COLUMN NAME 
USE SQL_STORE;
SELECT 
	first_name,birth_date,address
FROM CUSTOMERS;


-- WAQTF ANY 4 IMPORTANT COLUMNS FROM CORPORATES TABLE UNDER SQL_INVENTORY DATABASE
USE SQL_INVENTORY;
SELECT 
	COLLEAGUE_ID,
    REPORTING_ID,
    DATE_OF_JOINING,
    SALARY
FROM CORPORATES;


-- CONDITIONALS USING WHERE KEYWORD 

USE SQL_HR;
SELECT *
FROM EMPLOYEES
WHERE OFFICE_ID < 5;

-- WAQTF CUSTOMERS HAVING POINTS GREATER THAN 2000 IN CUSTOMERS TB UNDER SQL_STORE DB
USE SQL_STORE;
SELECT * 
FROM CUSTOMERS
WHERE POINTS > 2000;

-- I WANT SPECIFIC USER NAME 
USE SQL_STORE;
SELECT * 
FROM CUSTOMERS
WHERE FIRST_NAME = "ELKA";



-- ARITHMETIC OPERATORS (+, -, *, /)
USE SQL_STORE;
SELECT *,
	POINTS/2 AS "NEW POINTS" 
FROM CUSTOMERS;

-- WAQTF EMPLOYEES TABLE FROM HR DB AND GIVE AN INCREMENT OF 5K TO EVERYBODY AND CALL IT DIWALI_BONUS
USE SQL_HR;
SELECT * ,
	SALARY+5000 AS "DIWALI BONUS"
FROM EMPLOYEES;

-- LOGICAL OPERATORS (AND, OR, )
USE SQL_STORE;
SELECT *
FROM CUSTOMERS
WHERE POINTS < 2000 AND CUSTOMER_ID < 5;

USE SQL_STORE;
SELECT *
FROM CUSTOMERS
WHERE POINTS < 2000 OR CUSTOMER_ID < 5;

-- WAQTF INVOICE_TOTAL GREATER THAN 150 AND CLIENT_ID > 2 IN INVOICES TB UNDER INVOICING DB
USE SQL_INVOICING;
SELECT * 
FROM INVOICES
WHERE INVOICE_TOTAL > 150 AND CLIENT_ID > 2;


-- WANT TO PRINT CUSTOMERS WITH ID(5,7,10) 
USE SQL_STORE;
SELECT *
FROM CUSTOMERS
WHERE CUSTOMER_ID IN (5, 7, 10);


-- WAQTF ONLY THOSE OFFICE_ID WHICH BELONG TO MAHARASHTRA AND GUJARAT STATES IN OFFICES TB UNDER HR DB

USE SQL_HR;
SELECT OFFICE_ID
FROM OFFICES
WHERE STATE IN ("MH","GJ");

-- NOT OPERATOR (ALWAYS OPPOSITE OF  VALUE) 
USE SQL_STORE;
SELECT *
FROM CUSTOMERS
WHERE NOT CUSTOMER_ID = 5;


-- FETCH ONLY 1,2,3,4,6,7,8,9,11,12 ID's FROM OFFICES TB UNDER HR DB
USE SQL_STORE;
SELECT * 
FROM CUSTOMERS
WHERE NOT CUSTOMER_ID IN (5,10);