-- PRACTISE QUESTIONS 

-- WAQTJ INV TB WITH CLI TB UNDER INVOICING DB 
USE SQL_INVOICING;
SELECT * 
FROM INVOICES INV 
INNER JOIN CLIENTS CLI
ON INV.CLIENT_ID = CLI.CLIENT_ID;

-- WAQTJ EMP TB WITH OFF TB UNDER HR DB AND CALL 2 COLUMNS EACH FROM BOTH THE TABLES
USE SQL_HR;
 SELECT 
 E.FIRST_NAME,
 E.SALARY,
 O.OFFICE_ID,
 O.CITY
 FROM EMPLOYEES E
 JOIN OFFICES O
 ON E.OFFICE_ID = O.OFFICE_ID;

-- ------------------------------------------------------------- 

-- WAQT NATURALLY JOIN EMP TB WITH OFF TB UNDER HR DB

USE SQL_HR;
SELECT *
FROM EMPLOYEES 
NATURAL JOIN OFFICES;


-- WAQT CROSS JOIN CLIENTS TB WITH INVOICES TB UNDER INVOICING DB BUT YOU CANNOT USE THE WORD 'CROSS'

USE SQL_INVOICING;
SELECT*
FROM CLIENTS
JOIN INVOICES ;



-- WAQTJ CLI, INV AND PAYMENTS TB WITH EACH OTHER UNDER INVOICING DB AND KEEP ONLY 2 COLUMNS PER TB

USE SQL_INVOICING;
  SELECT
  C.client_id,
  C.name,
  I.invoice_id,
  I.invoice_total,
  p.payment_id,
  P.amount
FROM CLIENTS C
  JOIN INVOICES I
    ON C.client_id=I.client_id
  JOIN PAYMENTS P
    ON I.invoice_id =P.invoice_id;





-- WAQT COMPOUND JOIN INVOICES TB WITH PAYMENTS TB UNDER INVOICING DB 

USE SQL_INVOICING;
SELECT * 
FROM INVOICES INV
JOIN PAYMENTS PAY
ON INV.INVOICE_ID = PAY.INVOICE_ID AND INV.CLIENT_ID = PAY.CLIENT_ID;




-- WAQT SELF JOIN CORPORATES TB TO SHOW COLLEAGUES NAME IN FRONT OF THEIR REPORTING MANAGER UNDER INVENTORY DB

USE SQL_INVENTORY;
SELECT 
      C2.COL_NAME,
      C2.COLLEAGUE_ID, 
      C1.COL_NAME,
      C1.COLLEAGUE_ID
FROM CORPORATES C1
JOIN CORPORATES C2 
ON C1.COLLEAGUE_ID = C2.REPORTING_ID;


-- WAQT OUTER JOIN EMPLOYEES TB WITH OFFICES TB AND TRY BOTH THE VARIATIONS UNDER HR DB
USE SQL_HR;
  SELECT *
  FROM EMPLOYEES E RIGHT JOIN OFFICES O
   ON E.OFFICE_ID = O.OFFICE_ID;
   
   
-- SELF OUTER JOIN CORPORATES TB AND GIVE PREFERENCE TO MANAGER'S TB
USE SQL_INVENTORY;
SELECT 
C1.COLLEAGUE_ID AS EMPLOYEES_ID,
C1.COL_NAME AS EMPLOYEES,
C2.COL_NAME AS MANAGER
FROM CORPORATES C1 
RIGHT JOIN CORPORATES C2 
ON C1.REPORTING_ID = C2.COLLEAGUE_ID;



-- WAQT IMPLICITLY JOIN CUST TB WITH ORD TB UNDER STORE DB

USE SQL_STORE;
SELECT*
FROM CUSTOMERS C  , ORDERS O 
WHERE C.CUSTOMER_ID = O.CUSTOMER_ID;


-- WAQT CATEGORISE EMP BASED ON THEIR SALARIES FROM EMP_NEW TB UNDER HR DB AS FOLLOWS AND PUT THEM UNDER TIERS
-- 1. EMP EARNING LESS THAN 50K AS LOW_TIER
-- 2. EMP EARNING BETW 50K AND 1L AS MID_TIER
-- 3. ABOVE 1L AS TOP_TIER


USE SQL_HR;
SELECT *,
     "LOW_TIER" AS TIER 
FROM EMPLOYEES_NEW
WHERE SALARY < 50000
UNION 
SELECT *,
     "MID_TIER" AS TIER 
FROM EMPLOYEES_NEW
WHERE SALARY BETWEEN 50000 AND 100000
UNION 
SELECT *,
     "TOP_TIER" AS TIER 
FROM EMPLOYEES_NEW
WHERE SALARY > 100000;








